id: P54414742
initial_creation_type: input
source_metadata:
  title: Termas
  language: en
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    0aaf52dc412348a18c992cc427cd6f64:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    79fbd4d36e734ab7b57c1a990eedbccc:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    71781dcfdfe8441facffa7938c86050e:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    b035e0cbd1e94178836ea5f96f5ae22d:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    4fe1c3ff66d546b587289cd007950bfe:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    7909ff0b1aa749b9aacb236bfa0dcf00:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    f28a22177601415a88c575f1709add27:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    74eb1cabd1e64af8bebdc0c1cbc5a6e4:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    8acca3b008f9410699bcd46873b966b6:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    7667e12ea8e24d29b02a51f21b329b9a:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    b7aa8e7be6034c53b9ad06f510f8e4d9:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    920bad01c3e04a79abb3a4dc8d1b56e4:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    e6e2867d9523431e8b1e140f146612f9:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    f6de772cad334e16a5077c4b1925c6ce:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    1dd32f13eef74d2eaf9f4a5d7f78aaa8:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    77d0670a96e0421dbc7031b3da967b27:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    caaeb433ff85416797beea64407f4b2e:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    e002b57c2d964ed89e8848212cab428b:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    00ef34840883400c8fc2d8e965da8a07:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    b310286bfa544293aefa57034149d9f8:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    79a94495d2f54a5e948a478e4ac07a1a:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    b2418941143241ff81a8d7149a9d34d4:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    89f723cecfa745258aca34f991c65e6a:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    a5598d4eb72e47cc88131dd175239592:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    2984ec2ae7e14ce0bb967680f03681a5:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    53d20675c16a4ddf826f38363a540832:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    727b270880a54d5d8458ca917f853997:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    1170bddf285149f788179ccad575efba:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    73777c7947914a1d8200c1d6523fce3c:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    aa00f5dc36bd4142aa7cce80d22cb289:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    b77eed21570f42cb8de104797f05cc6c:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    3e3cf5f57b204e5eab395727c3c7e2cd:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    a806bae6513f435c84ffd50b18c7b5ae:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    0c23b002af2e4a87bf4c0337a9c9f23d:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    9bede5c4176b47e1ad6cbe8e78f97ab6:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    de26b0f55ac049f289c0ef6617c18a8a:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    007a81a7287a43398b9d20bcbaf044ea:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    e036ea48339843e4abd0ec5c34a68a42:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    a379ce9b9f304b7ea45ebf92e6bec0a5:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    3b3639cc28bc41ddafce777ba549d6c6:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    36237b015ec844fcb5530c6dc5efa757:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    ad01c26c3b804e3883684f998c6f75e8:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    d9ec56a827fb43249a508966f84f53f5:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    79fbca5edb6343a1a3e4181aefb16295:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    dd42de8c6c35438ea04f7a491fc1d403:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    a1152778427b4f018a3a50abaf250a40:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    a95c767b403d4c90b28c1feb838e32ab:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    1f3001c846ef4f12a36ce254cf22e2e7:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    3c107a01bdf949aabd33adff3a8e1e68:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    64288d47178f4a73aafb79b377b6e4d2:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    30efb63e7ba1434bb905ca7596b73c26:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    eba9ff35bbc74b83b1f7786666f49544:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    a94bd87c7d634376a4609f02b70e2bc9:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    db5cad3f1f074b40ad41b41287968484:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    c68df7157f8d43948143a10da8272d0d:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    e3f75f1d6998418d9582c35615021ceb:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    c5ffdec139114ec4835df01bd6c6c4d5:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    675e7f35f92e40fdb847669ecf314c98:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    8efc61c092e34670ae2bcdbf9c825521:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    652512cbc0824292af2da104c303e09e:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    b800a41fdd654f368fbd24ffbc92f248:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    1543011a6b384c7d824b8da0964b043b:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    3c20fda96f6944ddb705770e43b20860:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    9d0e515153f94ecd98429ad89e05c8a8:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    35cf93b99d89487a9bd0073ef3a557a0:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    f9e963aaa1564eedb8b939f7f4093e72:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    8169aa1b02f14fc386ab3deaf93bb500:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    b051b338a5de4a618e304173887834af:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    3eea352af64444758a29509faa9a5740:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    94c83ff9399949f99e0d60dab43a0661:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    5e71f535d07842a39f52f81120ade1c7:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    0e0b9c86ce0945d89004d3eb3716317c:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    a9ad614103f2495db3b072ae689c22f0:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    e50bd363e5be47f7939ec8bbfbd8cc84:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    3aab3a6965374068915bac3b25655cf1:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    42acbf0bf9084d42a5bbabb5676ec91c:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    c8798c334e6240e8b717997c4bfac7b1:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    e36440624c274fc9b1de518f4c452344:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    4341b1d4b4b64a7e8841d0c07c0ab45c:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    4dc5cfc79e324bee89b6a43edf8d6c91:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    e128caa2bcab4012af3c4390bbc62be0:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    8f470951e3674a49b30e848f60578456:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    06125704dc914e01874ea64e6983e02d:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    73b76386cdf4417d8f78faa128ff8de8:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    be657b14f9ef4cb3aba32b68f2bcb4d2:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    51e051ab75e44f729f883e24d4ba2fcc:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    a53126d837e44f3580bbfa910d21f3ee:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    4e90162f6e5946348aa6fab7cc932c86:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    38ea789e28de4cabb0533316064aa61f:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    573eae40b18946bda22298bf7a700683:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    8947195bdaed4e97b0b6252457809e35:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    84e5b8adb388439f8c655f497d13d7db:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    26ef441deb164747aabd24e4d7aa9747:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    a187c76f31744c00ab79b106bfe85e9d:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    984d0683993540f682774ba363022438:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    99dca3a8d7f84088864079c9faabb69a:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    27bfbfd81a834f2ba0826b1ba484fd05:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    f33bd5c872dd4800aa1f47dc50835596:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    bddd1fa5f200426bac7604e6a965cb5b:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    2c66a3f6c21940cf8fcc0b0d61c6bef7:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.617038'
last_modified_at: '2022-03-01T06:17:48.617045'
